# Forest Fire Area Prediction

# Import Library

Imported some commonly used libraries for data manipulation (NumPy, Pandas), data visualization (Matplotlib, Seaborn), and potentially statistical analysis (Seaborn). These libraries are widely used in machine learning tasks. If you have a specific task or analysis in mind, you can proceed with your code using these libraries.

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# Loaded a dataset

In [4]:
df= pd.read_csv("forestfires.csv")
df

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [5]:
df.shape

(517, 13)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X       517 non-null    int64  
 1   Y       517 non-null    int64  
 2   month   517 non-null    object 
 3   day     517 non-null    object 
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    int64  
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
 12  area    517 non-null    float64
dtypes: float64(8), int64(3), object(2)
memory usage: 52.6+ KB


# Data analysis

The code df.isnull().sum().sum() calculates the total number of missing values in your DataFrame (df). It sums up the count of missing values for each column and then provides the overall count.


In [7]:
df.isnull().sum().sum()

0

# Data Preprocessing

In [8]:
df.month.value_counts()

month
aug    184
sep    172
mar     54
jul     32
feb     20
jun     17
oct     15
apr      9
dec      9
jan      2
may      2
nov      1
Name: count, dtype: int64

In [9]:
df.day.value_counts()

day
sun    95
fri    85
sat    84
mon    74
tue    64
thu    61
wed    54
Name: count, dtype: int64

# Label & Orginal Encoding

The LabelEncoder is commonly used to convert categorical labels into numerical format, which is necessary for many machine learning algorithms that require numerical input.

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le=LabelEncoder()

In [12]:
l_enc= df[["month","day"]]

In [13]:
le.fit_transform(l_enc["month"])

array([ 7, 10, 10,  7,  7,  1,  1,  1, 11, 11, 11, 11,  1, 11, 11, 11,  7,
       10,  7,  0, 11, 11,  6,  1,  1,  1, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 10, 10, 10,  7,  5,  1,  1, 11, 11, 11, 11,  5,  7,  7, 11,
        1,  1,  1,  1, 11, 11, 10,  3,  3,  7,  7,  1,  1,  1,  1, 11, 11,
       11,  7,  7, 11,  7,  1, 11,  3,  3,  7,  1,  1,  1,  1,  1,  1,  1,
       11, 11, 11, 11,  7,  1,  7,  1,  1,  1, 11,  3,  7,  1,  1,  1,  1,
        1, 11,  4,  7,  7,  1, 11, 11,  7,  7, 11, 11,  7,  7,  7,  7,  7,
        1,  1,  1, 11, 11, 11, 10,  7, 11, 10, 10,  3,  7,  7, 11,  7,  1,
       11, 11,  5, 11, 11,  1,  1,  5,  1,  1,  7, 11,  1, 11,  6,  5,  5,
       11, 11,  1, 11,  1,  1, 11,  7,  1,  7, 11, 11,  7,  1,  1,  7,  1,
       11,  1,  1, 11,  1,  1,  0,  1, 11,  1, 11, 10,  3, 10,  1, 11,  7,
       11,  7,  7,  7,  1,  1, 11,  1,  1,  0, 11, 11, 11, 11,  7,  3, 10,
        7, 11,  1, 11, 11, 11, 10,  1, 11,  7,  7,  7, 11, 11, 11,  7,  1,
       11,  7,  5, 11, 11

In [14]:
l_enc["month_L_enc"] = le.fit_transform(l_enc["month"])
l_enc

C:\Users\patil\AppData\Local\Temp\ipykernel_14204\2940176336.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l_enc["month_L_enc"] = le.fit_transform(l_enc["month"])


month  day  month_L_enc
0     mar  fri            7
1     oct  tue           10
2     oct  sat           10
3     mar  fri            7
4     mar  sun            7
..    ...  ...          ...
512   aug  sun            1
513   aug  sun            1
514   aug  sun            1
515   aug  sat            1
516   nov  tue            9

[517 rows x 3 columns]

In [15]:
order_Label = {"sat":7,"fri":6,"thu":5,"wed":4,"tue":3,"mon":2,"sun":1}

In [16]:
# Now we map the the dictionary "order_Label" with the class "day" 
l_enc["day_ord_enc"] = l_enc["day"].map(order_Label)
l_enc

C:\Users\patil\AppData\Local\Temp\ipykernel_14204\1933352912.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l_enc["day_ord_enc"] = l_enc["day"].map(order_Label)


month  day  month_L_enc  day_ord_enc
0     mar  fri            7            6
1     oct  tue           10            3
2     oct  sat           10            7
3     mar  fri            7            6
4     mar  sun            7            1
..    ...  ...          ...          ...
512   aug  sun            1            1
513   aug  sun            1            1
514   aug  sun            1            1
515   aug  sat            1            7
516   nov  tue            9            3

[517 rows x 4 columns]

# other method convert variable

In [17]:
month_map = {'jan':1, 'feb':2, 'mar':3, 
             'apr':4, 'may':5, 'jun':6, 
             'jul':7, 'aug':8, 'sep':9, 
             'oct':10, 'nov':11, 'dec':12}

day_map = {'mon':1, 'tue':2, 'wed':3,
          'thu':4, 'fri':5, 'sat':6, 'sun':7}

df.month = df.month.map(month_map)
df.day = df.day.map(day_map)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X       517 non-null    int64  
 1   Y       517 non-null    int64  
 2   month   517 non-null    int64  
 3   day     517 non-null    int64  
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    int64  
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
 12  area    517 non-null    float64
dtypes: float64(8), int64(5)
memory usage: 52.6 KB


# Standardization & Splitting

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

importing StandardScaler for feature scaling and train_test_split for splitting your data into training and testing sets. These are common preprocessing steps in machine learning.

In [20]:
# Splitting Data
# X represents the input features (all columns except 'Grade')
X=df.drop(['area'],axis=1)
# y represents the target variable ('Grade')
y=df['area']
print('shape of X', X.shape)
print('shape of y', y.shape)

shape of X (517, 12)
shape of y (517,)


In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
print('shape of the X_train= ', X_train.shape)
print('shape of the y_train= ', y_train.shape)
print('shape of the X_test= ', X_test.shape)
print('shape of the y_test= ', y_test.shape)


shape of the X_train=  (413, 12)
shape of the y_train=  (413,)
shape of the X_test=  (104, 12)
shape of the y_test=  (104,)


# Feature Scaling

Feature scaling is important for many machine learning algorithms to ensure that all features contribute equally to the model's performance. train_test_split is used to divide your dataset into training and testing sets, allowing you to assess the model's performance on unseen data.

In [22]:
sc = StandardScaler()

In [23]:
sc.fit(X_train)

StandardScaler()

In [24]:
sc.mean_

array([4.69249395e+00, 4.29782082e+00, 7.49636804e+00, 4.22760291e+00,
       9.07409201e+01, 1.08040920e+02, 5.44986925e+02, 9.05762712e+00,
       1.87878935e+01, 4.45569007e+01, 4.05060533e+00, 2.42130751e-02])

In [25]:
sc.scale_

array([  2.28053492,   1.20969454,   2.2737818 ,   2.09149397,
         4.5192562 ,  62.067655  , 247.41300684,   4.70833285,
         5.9366387 ,  16.25239136,   1.81519838,   0.32787329])

In [26]:
X_train.describe()

X           Y       month         day        FFMC         DMC  \
count  413.000000  413.000000  413.000000  413.000000  413.000000  413.000000   
mean     4.692494    4.297821    7.496368    4.227603   90.740920  108.040920   
std      2.283301    1.211162    2.276540    2.094031    4.524737   62.142934   
min      1.000000    2.000000    1.000000    1.000000   50.400000    2.400000   
25%      3.000000    4.000000    7.000000    2.000000   90.200000   56.700000   
50%      4.000000    4.000000    8.000000    5.000000   91.600000  108.000000   
75%      7.000000    5.000000    9.000000    6.000000   92.900000  141.200000   
max      9.000000    9.000000   12.000000    7.000000   96.200000  291.300000   

               DC         ISI        temp          RH        wind        rain  
count  413.000000  413.000000  413.000000  413.000000  413.000000  413.000000  
mean   544.986925    9.057627   18.787893   44.556901    4.050605    0.024213  
std    247.713083    4.714043    5.943839   16.272103    1.817400    0.328271  
min      9.300000    0.400000    2.200000   15.000000    0.400000    0.000000  
25%    430.800000    6.300000   15.400000   33.000000    2.700000    0.000000  
50%    658.200000    8.400000   19.200000   42.000000    4.000000    0.000000  
75%    706.800000   11.000000   22.900000   53.000000    4.900000    0.000000  
max    860.600000   56.100000   33.300000   99.000000    9.400000    6.400000

In [27]:
X_train_sc=sc.transform(X_train)
X_test_sc=sc.transform(X_test)

In [28]:
X_train_sc = pd.DataFrame(X_train_sc, columns= ['X','Y','month','day','FFMC','DMC','DC','ISI','temp','RH','wind','rain'])
X_test_sc = pd.DataFrame(X_test_sc, columns= ['X','Y','month','day','FFMC','DMC','D','ISI','temp','RH','wind','rain'])

In [29]:

X_train

X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain
390  7  4      2    1  84.7    9.5   58.3   4.1   7.5  71   6.3   0.0
296  6  4      6    7  90.4   89.5  290.8   6.4  14.3  46   1.8   0.0
249  3  4      8    3  93.1  157.3  666.7  13.5  21.7  40   0.4   0.0
126  3  5      3    1  87.6   52.2  103.8   5.0   9.0  49   2.2   0.0
315  3  4      9    3  91.2  134.7  817.5   7.2  18.5  30   2.7   0.0
..  .. ..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...
28   6  3      9    6  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0
361  4  3      9    5  92.5  122.0  789.7  10.2  17.3  45   4.0   0.0
436  8  6      8    1  92.1  207.0  672.6   8.2  26.8  35   1.3   0.0
485  2  4      8    1  95.0  135.5  596.3  21.3  30.6  28   3.6   0.0
57   4  3     10    7  92.6   46.5  691.8   8.8  13.8  50   2.7   0.0

[413 rows x 12 columns]

In [30]:
X_train_sc.head()

X         Y     month       day      FFMC       DMC        DC  \
0  1.011827 -0.246195 -2.417280 -1.543204 -1.336707 -1.587637 -1.967103   
1  0.573333 -0.246195 -0.658097  1.325558 -0.075437 -0.298721 -1.027379   
2 -0.742148 -0.246195  0.221495 -0.586950  0.522006  0.793635  0.491943   
3 -0.742148  0.580460 -1.977484 -1.543204 -0.695008 -0.899678 -1.783200   
4 -0.742148 -0.246195  0.661291 -0.586950  0.101583  0.429516  1.101450   

        ISI      temp        RH      wind      rain  
0 -1.052947 -1.901395  1.627028  1.239200 -0.073849  
1 -0.564452 -0.755965  0.088793 -1.239867 -0.073849  
2  0.943513  0.490531 -0.280383 -2.011133 -0.073849  
3 -0.861797 -1.648726  0.273381 -1.019506 -0.073849  
4 -0.394540 -0.048494 -0.895677 -0.744054 -0.073849

In [31]:
X_train_sc.describe()

X             Y         month           day          FFMC  \
count  4.130000e+02  4.130000e+02  4.130000e+02  4.130000e+02  4.130000e+02   
mean   1.193557e-16 -2.236575e-16 -1.075277e-17 -4.301106e-17 -1.520441e-15   
std    1.001213e+00  1.001213e+00  1.001213e+00  1.001213e+00  1.001213e+00   
min   -1.619135e+00 -1.899505e+00 -2.857076e+00 -1.543204e+00 -8.926451e+00   
25%   -7.421478e-01 -2.461951e-01 -2.183006e-01 -1.065077e+00 -1.196923e-01   
50%   -3.036542e-01 -2.461951e-01  2.214953e-01  3.693040e-01  1.900932e-01   
75%    1.011827e+00  5.804599e-01  6.612912e-01  8.474311e-01  4.777512e-01   
max    1.888814e+00  3.887080e+00  1.980679e+00  1.325558e+00  1.207960e+00   

                DMC            DC           ISI          temp            RH  \
count  4.130000e+02  4.130000e+02  4.130000e+02  4.130000e+02  4.130000e+02   
mean  -4.301106e-17 -2.365608e-16 -2.505394e-16  2.580664e-16  1.161299e-16   
std    1.001213e+00  1.001213e+00  1.001213e+00  1.001213e+00  1.001213e+00   
min   -1.702029e+00 -2.165153e+00 -1.838788e+00 -2.794156e+00 -1.818619e+00   
25%   -8.271767e-01 -4.615235e-01 -5.856908e-01 -5.706754e-01 -7.110892e-01   
50%   -6.592821e-04  4.575874e-01 -1.396730e-01  6.941749e-02 -1.573246e-01   
75%    5.342409e-01  6.540201e-01  4.125394e-01  6.926658e-01  5.194989e-01   
max    2.952570e+00  1.275653e+00  9.991301e+00  2.444499e+00  3.349852e+00   

               wind          rain  
count  4.130000e+02  4.130000e+02  
mean  -8.602212e-18  4.301106e-18  
std    1.001213e+00  1.001213e+00  
min   -2.011133e+00 -7.384888e-02  
25%   -7.440538e-01 -7.384888e-02  
50%   -2.787868e-02 -7.384888e-02  
75%    4.679349e-01 -7.384888e-02  
max    2.947003e+00  1.944589e+01

In [32]:
X_train_sc.describe().round(2)

X       Y   month     day    FFMC     DMC      DC     ISI    temp  \
count  413.00  413.00  413.00  413.00  413.00  413.00  413.00  413.00  413.00   
mean     0.00   -0.00   -0.00   -0.00   -0.00   -0.00   -0.00   -0.00    0.00   
std      1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00   
min     -1.62   -1.90   -2.86   -1.54   -8.93   -1.70   -2.17   -1.84   -2.79   
25%     -0.74   -0.25   -0.22   -1.07   -0.12   -0.83   -0.46   -0.59   -0.57   
50%     -0.30   -0.25    0.22    0.37    0.19   -0.00    0.46   -0.14    0.07   
75%      1.01    0.58    0.66    0.85    0.48    0.53    0.65    0.41    0.69   
max      1.89    3.89    1.98    1.33    1.21    2.95    1.28    9.99    2.44   

           RH    wind    rain  
count  413.00  413.00  413.00  
mean     0.00   -0.00    0.00  
std      1.00    1.00    1.00  
min     -1.82   -2.01   -0.07  
25%     -0.71   -0.74   -0.07  
50%     -0.16   -0.03   -0.07  
75%      0.52    0.47   -0.07  
max      3.35    2.95   19.45

# Implement Model

# Linear Regression

Replace X_train, y_train, X_test, and y_test with your actual training and testing sets. The LinearRegression model is now trained on your training data, and you can evaluate its performance using metrics like mean squared error.

In [33]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [34]:
regressor.score(X_test,y_test)

-0.007611241260526036

# K- NearestNeighbors Regression

The k-nearest neighbors algorithm predicts the target variable by considering the k-nearest data points in the training set. It's essential to choose an appropriate value for n_neighbors based on the characteristics of your data.
 

In [35]:
from sklearn.neighbors import KNeighborsRegressor


In [36]:
regressor = KNeighborsRegressor(n_neighbors=5)
regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [37]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [38]:
sc.fit(X_train)

StandardScaler()

In [39]:
regressor.score(X_test,y_test)


-1.6190085650681802

# Implement Random Forest Regression

Random Forest is an ensemble method that combines multiple decision trees to improve predictive performance and control overfitting. It can be a powerful tool for regression tasks

In [40]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [41]:
rd = RandomForestRegressor(n_estimators=40, random_state=51)


In [42]:
rd.fit(X_train, y_train)


RandomForestRegressor(n_estimators=40, random_state=51)

In [43]:
y_pred = rd.predict(X_test)

In [44]:
rd.score(X_test,y_test)

-3.1148850321469856

In [45]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

# Print the Root Mean Squared Error (RMSE)
print('Root Mean Squared Error:', rmse)

Root Mean Squared Error: 65.37588277865657


In [46]:
from sklearn.model_selection import cross_val_score

In [47]:
score_rf=cross_val_score(RandomForestRegressor(n_estimators=5),X_train,y_train,cv=5)
print(score_rf)
print("Avg:",np.average(score_rf))

[-0.08908886 -9.3281654   0.01846978 -0.12051604 -3.12540431]
Avg: -2.5289409657218167


In [48]:
scores1 = cross_val_score(RandomForestRegressor(n_estimators=5),X_train,y_train,cv=5)
print("Avg Score for Estimators=5 and CV=5 :",np.average(scores1))

Avg Score for Estimators=5 and CV=5 : -1.2020697726560716


# Implement Decision Tree Regression

In [49]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

# Assuming X_train, X_test, y_train, y_test are already defined

# Initialize the Decision Tree Regressor
decision_tree_model = DecisionTreeRegressor(random_state=51)

# Train the model
decision_tree_model.fit(X_train, y_train)

decision_tree_model.score(X_test,y_test)

-17.19268599205353

In [50]:
# Make predictions on the test set
y_pred = decision_tree_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

# Print the Root Mean Squared Error (RMSE)
print('Root Mean Squared Error:', rmse)

Root Mean Squared Error: 137.4634138301058
